# pyproject.toml
[tool.black]
line-length = 100
target-version = ["py310"]

[tool.ruff]
line-length = 100
target-version = "py310"

[tool.ruff.lint]
select = ["E", "F", "I"]
# ignore = []
# extend-select = []
# per-file-ignores = { "src/__init__.py" = ["F401"] }

