name: CI (Python + Playwright)

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
          cache-dependency-path: requirements.txt
      - name: Install runtime + dev tools
        run: |
          python -m pip install -r requirements.txt
          python -m pip install --upgrade ruff black
      - name: Ruff (lint)
        run: ruff check .
      - name: Black (format check)
        run: black --check .

  run:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
          cache-dependency-path: requirements.txt
      - name: Install Playwright + deps
        run: |
          pip install -r requirements.txt
          python -m playwright install --with-deps
      - name: Run challenge (headless, perf) on sample data
        env:
          PYTHONUNBUFFERED: "1"
        run: |
          mkdir -p screenshots
          python -m src.main --file data/sample.csv --headless --perf --log-level WARNING
          [ -f screenshots/run_summary.json ] && cat screenshots/run_summary.json || true
      - name: Upload screenshots
        uses: actions/upload-artifact@v4
        with:
          name: screenshots
          path: screenshots/*
          if-no-files-found: warn
